# Generated by Django 5.0.2 on 2024-02-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('tashhis', models.TextField()),
                ('kishi_soni', models.PositiveSmallIntegerField()),
                ('summa', models.FloatField()),
                ('tuzaldi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shifokor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('ish_vaqti', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('narx', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('band', models.BooleanField()),
                ('joy', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.buyurtma')),
            ],
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='shifokor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.shifokor'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='xizmat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.xizmat'),
        ),
        migrations.AddField(
            model_name='xizmat',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.xona'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.xona'),
        ),
    ]
